### Task 1.1
* Name:LI WAN
* Student Number:223718804
* E-mail:s223718804@deakin.edu.au
* Course:SIT720
---

In [9]:
# Q1
name = "LI WAN"

# Print characters at even positions
even_positions = name[::2]
print(f"Characters at even positions: {even_positions}")

# Print characters at odd positions
odd_positions = name[1::2]
print(f"Characters at odd positions: {odd_positions}")

Characters at even positions: L A
Characters at odd positions: IWN


In [1]:
# Q2
import random

# Function to generate random values
def generate_random_values():
    names = ["Aj", "Belinda", "Celine", "Star", "Sam"]
    courses = ["Chemistry", "Computer Science", "History", "Physics", "Math"]
    domains = ["gmail.com", "163.com", "outlook.com", "hotmail.com", "qq.com"]

    # Shuffle the lists to get random values
    random.shuffle(names)
    random.shuffle(courses)
    random.shuffle(domains)

    return names, courses, domains

# Assign random values to variables
student_names, course_names, email_domains = generate_random_values()

# Print the values
print(f"Student names: {student_names}")
print(f"Course names: {course_names}")
print(f"Email addresses: {[f'{name.lower()}_{course.lower()}@{domain}' for name, course, domain in zip(student_names, course_names, email_domains)]}")

Student names: ['Aj', 'Sam', 'Celine', 'Star', 'Belinda']
Course names: ['Chemistry', 'Physics', 'Math', 'Computer Science', 'History']
Email addresses: ['aj_chemistry@163.com', 'sam_physics@gmail.com', 'celine_math@outlook.com', 'star_computer science@hotmail.com', 'belinda_history@qq.com']


In [6]:
# Q3
student_data = {
    'Student name': student_names,
    'Course name': course_names,
    'Email Address': [f'{name.lower()}_{course.lower()}@{domain}' for name, course, domain in zip(student_names, course_names, email_domains)]
}

# Print the dictionary
print("Student Data:")
for key, value in student_data.items():
    print(f"{key}: {value}")

Student Data:
Student name: ['Sam', 'Aj', 'Celine', 'Belinda', 'Star']
Course name: ['Math', 'Chemistry', 'Physics', 'History', 'Computer Science']
Email Address: ['sam_math@outlook.com', 'aj_chemistry@gmail.com', 'celine_physics@qq.com', 'belinda_history@hotmail.com', 'star_computer science@163.com']


In [8]:
# Q4
# Define the 'energy' string variable
energy = 'Biomass'

# Check the value of the 'energy' variable
if energy == 'Fossil':
    print("Natural gas")
else:
    print("Solar power")

Solar power


In [12]:
# Q5
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Print prime numbers between 0 and 100
print("Prime numbers between 0 and 100:")
for number in range(101):
    if is_prime(number):
        print(number)

Prime numbers between 0 and 100:
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


In [9]:
# Q7 
# Define functions for addition, multiplication, division, and subtraction
def Addition(x, y):
    return x + y

def Multiplication(x, y):
    return x * y

def Division(x, y):
    if y != 0:
        return x / y
    else:
        return "Cannot divide by zero."

def Subtraction(x, y):
    return x - y

# Call the functions with (4, 7) 
x, y = 4, 7

result_addition = Addition(x, y)
result_multiplication = Multiplication(x, y)
result_division = Division(x, y)
result_subtraction = Subtraction(x, y)

# Print the outputs
print(f"Addition: {result_addition}")
print(f"Multiplication: {result_multiplication}")
print(f"Division: {result_division}")
print(f"Subtraction: {result_subtraction}")

Addition: 11
Multiplication: 28
Division: 0.5714285714285714
Subtraction: -3


In [16]:
# Q8
import numpy as np

# Create an 8x8 Identity matrix
identity_matrix = np.eye(8)

# Create an 8x4 random matrix
random_matrix = np.random.rand(8, 4)

# Multiply the identity matrix with the random matrix
result_matrix = np.dot(identity_matrix, random_matrix)

# Display the matrices
print("Identity Matrix (8x8):")
print(identity_matrix)
print("\nRandom Matrix (8x4):")
print(random_matrix)
print("\nResult Matrix after multiplication:")
print(result_matrix)

Identity Matrix (8x8):
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]

Random Matrix (8x4):
[[0.87081793 0.07457418 0.25480637 0.31685648]
 [0.94388175 0.43833771 0.72600802 0.78557247]
 [0.94307022 0.16789849 0.36858331 0.81736497]
 [0.86801863 0.45239474 0.09768585 0.33288667]
 [0.85927489 0.20991543 0.76948756 0.36682044]
 [0.49339247 0.20525796 0.47659793 0.7364305 ]
 [0.64422576 0.56581623 0.20648542 0.30820598]
 [0.923942   0.14247601 0.73151954 0.89885726]]

Result Matrix after multiplication:
[[0.87081793 0.07457418 0.25480637 0.31685648]
 [0.94388175 0.43833771 0.72600802 0.78557247]
 [0.94307022 0.16789849 0.36858331 0.81736497]
 [0.86801863 0.45239474 0.09768585 0.33288667]
 [0.85927489 0.20991543 0.76948756 0.36682044]
 [0.49339247 0.20525796 0.47659793 0.7364305 ]
 [0.64422576 0.56581623 0.20648542 0.30820

In [17]:
# Q9
# Create an 8x9 matrix with random values
original_matrix = np.random.rand(8, 9)

# Print the original matrix
print("Original Matrix (8x9):")
print(original_matrix)

# Transpose the matrix
transposed_matrix = np.transpose(original_matrix)

# Print the transposed matrix
print("\nTransposed Matrix (9x8):")
print(transposed_matrix)


Original Matrix (8x9):
[[0.42411445 0.32882822 0.49049912 0.88896006 0.95244499 0.13456126
  0.67320987 0.98300638 0.29944185]
 [0.37352784 0.33333804 0.31475086 0.72405143 0.39293992 0.75192921
  0.15352448 0.34514698 0.22689127]
 [0.07842286 0.5614458  0.26107054 0.15005205 0.29243784 0.90871456
  0.73204129 0.99250113 0.7499537 ]
 [0.10194862 0.33973934 0.04797601 0.58431036 0.94583594 0.0536265
  0.86979704 0.89925652 0.19338075]
 [0.86419623 0.78198347 0.75018598 0.4704352  0.69384994 0.64289963
  0.21104366 0.1780705  0.21321172]
 [0.63075038 0.17133743 0.64433836 0.77374412 0.60973362 0.86151804
  0.27247768 0.55018109 0.14331965]
 [0.4471771  0.7874462  0.01226523 0.36462928 0.59164461 0.27510632
  0.26199333 0.9867413  0.01867205]
 [0.7547443  0.06587853 0.96306904 0.09424086 0.18111897 0.10868231
  0.46534952 0.48011396 0.37283029]]

Transposed Matrix (9x8):
[[0.42411445 0.37352784 0.07842286 0.10194862 0.86419623 0.63075038
  0.4471771  0.7547443 ]
 [0.32882822 0.33333804 0.

In [11]:
# Q10
import pandas as pd
local_path = r'E:\2-学习\1-Deakin\24-T1\SIT720\Task\pedestrian-counting-system-monthly-counts-per-hour.csv'
df=pd.read_csv(local_path, comment='#')
df.head()

Sensor_Name      SensingDateTime(Hour)  LocationID  Direction_1  \
0    SprFli_T  2023-04-25T07:00:00+10:00          75           36   
1    SprFli_T  2023-04-25T10:00:00+10:00          75           28   
2    SprFli_T  2023-04-25T11:00:00+10:00          75           63   
3    SprFli_T  2023-04-25T12:00:00+10:00          75           85   
4    SprFli_T  2023-04-25T18:00:00+10:00          75          365   

   Direction_2  Total_of_Directions                    Location  
0           17                   53  -37.81515276, 144.97467661  
1           50                   78  -37.81515276, 144.97467661  
2           63                  126  -37.81515276, 144.97467661  
3           89                  174  -37.81515276, 144.97467661  
4           59                  424  -37.81515276, 144.97467661

In [12]:
# Print the number of data instances and variables
num_instances, num_variables = df.shape
print(f"Number of data instances: {num_instances}")
print(f"Number of variables: {num_variables}")

# Calculate the mean of the third variable ('LocationID')
location_id_mean = df['LocationID'].mean()

# Deduct the mean from the original values of the 'LocationID' variable
df['Modified_LocationID'] = df['LocationID'] - location_id_mean

# Print both original and modified values of the 'LocationID' variable
print("\nOriginal values of 'LocationID':")
print(df['LocationID'])

print("\nModified values of 'LocationID' (after deducting mean):")
print(df['Modified_LocationID'])

Number of data instances: 525005
Number of variables: 7

Original values of 'LocationID':
0          75
1          75
2          75
3          75
4          75
         ... 
525000    142
525001    142
525002    142
525003    142
525004    142
Name: LocationID, Length: 525005, dtype: int64

Modified values of 'LocationID' (after deducting mean):
0         21.822695
1         21.822695
2         21.822695
3         21.822695
4         21.822695
            ...    
525000    88.822695
525001    88.822695
525002    88.822695
525003    88.822695
525004    88.822695
Name: Modified_LocationID, Length: 525005, dtype: float64
